// Code generated by MockGen. DO NOT EDIT.
// Source: healthcheck.go
//
// Generated by this command:
//
//	mockgen -source=healthcheck.go -destination=healthcheck_mock.go -package=healthcheck
//

// Package healthcheck is a generated GoMock package.
package healthcheck

import (
	reflect "reflect"

	process "github.com/bibendi/gruf-relay/internal/process"
	gomock "go.uber.org/mock/gomock"
)

// MockBalancer is a mock of Balancer interface.
type MockBalancer struct {
	ctrl     *gomock.Controller
	recorder *MockBalancerMockRecorder
	isgomock struct{}
}

// MockBalancerMockRecorder is the mock recorder for MockBalancer.
type MockBalancerMockRecorder struct {
	mock *MockBalancer
}

// NewMockBalancer creates a new mock instance.
func NewMockBalancer(ctrl *gomock.Controller) *MockBalancer {
	mock := &MockBalancer{ctrl: ctrl}
	mock.recorder = &MockBalancerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalancer) EXPECT() *MockBalancerMockRecorder {
	return m.recorder
}

// AddProcess mocks base method.
func (m *MockBalancer) AddProcess(arg0 process.Process) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProcess", arg0)
}

// AddProcess indicates an expected call of AddProcess.
func (mr *MockBalancerMockRecorder) AddProcess(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcess", reflect.TypeOf((*MockBalancer)(nil).AddProcess), arg0)
}

// RemoveProcess mocks base method.
func (m *MockBalancer) RemoveProcess(arg0 process.Process) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveProcess", arg0)
}

// RemoveProcess indicates an expected call of RemoveProcess.
func (mr *MockBalancerMockRecorder) RemoveProcess(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProcess", reflect.TypeOf((*MockBalancer)(nil).RemoveProcess), arg0)
}
