// Code generated by MockGen. DO NOT EDIT.
// Source: healthcheck.go
//
// Generated by this command:
//
//	mockgen -source=healthcheck.go -destination=healthcheck_mock.go -package=healthcheck
//

// Package healthcheck is a generated GoMock package.
package healthcheck

import (
	reflect "reflect"

	worker "github.com/bibendi/gruf-relay/internal/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockBalancer is a mock of Balancer interface.
type MockBalancer struct {
	ctrl     *gomock.Controller
	recorder *MockBalancerMockRecorder
	isgomock struct{}
}

// MockBalancerMockRecorder is the mock recorder for MockBalancer.
type MockBalancerMockRecorder struct {
	mock *MockBalancer
}

// NewMockBalancer creates a new mock instance.
func NewMockBalancer(ctrl *gomock.Controller) *MockBalancer {
	mock := &MockBalancer{ctrl: ctrl}
	mock.recorder = &MockBalancerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalancer) EXPECT() *MockBalancerMockRecorder {
	return m.recorder
}

// AddWorker mocks base method.
func (m *MockBalancer) AddWorker(arg0 worker.Worker) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWorker", arg0)
}

// AddWorker indicates an expected call of AddWorker.
func (mr *MockBalancerMockRecorder) AddWorker(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorker", reflect.TypeOf((*MockBalancer)(nil).AddWorker), arg0)
}

// RemoveWorker mocks base method.
func (m *MockBalancer) RemoveWorker(arg0 worker.Worker) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveWorker", arg0)
}

// RemoveWorker indicates an expected call of RemoveWorker.
func (mr *MockBalancerMockRecorder) RemoveWorker(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorker", reflect.TypeOf((*MockBalancer)(nil).RemoveWorker), arg0)
}
