# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/jobs.proto

require 'google/protobuf'


descriptor_data = "\n\x11\x63onfig/jobs.proto\x12\x04\x64\x65mo\"\x17\n\tGetJobReq\x12\n\n\x02id\x18\x01 \x01(\x04\"&\n\nGetJobResp\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t25\n\x04Jobs\x12-\n\x06GetJob\x12\x0f.demo.GetJobReq\x1a\x10.demo.GetJobResp\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Demo
  GetJobReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.GetJobReq").msgclass
  GetJobResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.GetJobResp").msgclass
end
