// Code generated by MockGen. DO NOT EDIT.
// Source: proxy.go
//
// Generated by this command:
//
//	mockgen -source=proxy.go -destination=proxy_mock.go -package proxy
//

// Package proxy is a generated GoMock package.
package proxy

import (
	reflect "reflect"

	worker "github.com/bibendi/gruf-relay/internal/worker"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockBalancer is a mock of Balancer interface.
type MockBalancer struct {
	ctrl     *gomock.Controller
	recorder *MockBalancerMockRecorder
	isgomock struct{}
}

// MockBalancerMockRecorder is the mock recorder for MockBalancer.
type MockBalancerMockRecorder struct {
	mock *MockBalancer
}

// NewMockBalancer creates a new mock instance.
func NewMockBalancer(ctrl *gomock.Controller) *MockBalancer {
	mock := &MockBalancer{ctrl: ctrl}
	mock.recorder = &MockBalancerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalancer) EXPECT() *MockBalancerMockRecorder {
	return m.recorder
}

// Next mocks base method.
func (m *MockBalancer) Next() worker.Worker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(worker.Worker)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockBalancerMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockBalancer)(nil).Next))
}

// MockPulledClientConn is a mock of PulledClientConn interface.
type MockPulledClientConn struct {
	ctrl     *gomock.Controller
	recorder *MockPulledClientConnMockRecorder
	isgomock struct{}
}

// MockPulledClientConnMockRecorder is the mock recorder for MockPulledClientConn.
type MockPulledClientConnMockRecorder struct {
	mock *MockPulledClientConn
}

// NewMockPulledClientConn creates a new mock instance.
func NewMockPulledClientConn(ctrl *gomock.Controller) *MockPulledClientConn {
	mock := &MockPulledClientConn{ctrl: ctrl}
	mock.recorder = &MockPulledClientConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPulledClientConn) EXPECT() *MockPulledClientConnMockRecorder {
	return m.recorder
}

// Conn mocks base method.
func (m *MockPulledClientConn) Conn() *grpc.ClientConn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Conn")
	ret0, _ := ret[0].(*grpc.ClientConn)
	return ret0
}

// Conn indicates an expected call of Conn.
func (mr *MockPulledClientConnMockRecorder) Conn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Conn", reflect.TypeOf((*MockPulledClientConn)(nil).Conn))
}

// Return mocks base method.
func (m *MockPulledClientConn) Return() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Return")
}

// Return indicates an expected call of Return.
func (mr *MockPulledClientConnMockRecorder) Return() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Return", reflect.TypeOf((*MockPulledClientConn)(nil).Return))
}
