apiVersion: apps/v1
kind: Deployment
metadata:
  name: gruf-relay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gruf-relay
  template:
    metadata:
      labels:
        app: gruf-relay
    spec:
      containers:
      - name: gruf-relay
        image: gruf-relay:${VERSION}
        command: ["bundle", "exec", "${CMD}"]
        env:
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9394"
        - name: PROMETHEUS_EXPORTER_PATH
          value: /metrics
        - name: RAILS_LOG_LEVEL
          value: debug
        ports:
        - containerPort: 8080
        - containerPort: 5555
        - containerPort: 9394
        # startupProbe:
        #   httpGet:
        #     path: /startup
        #     port: 5555
        #   failureThreshold: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 5555
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /liveness
        #     port: 5555
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
