apiVersion: apps/v1
kind: Deployment
metadata:
  name: gruf-relay
spec:
  replicas: 6
  selector:
    matchLabels:
      app: gruf
  template:
    metadata:
      labels:
        app: gruf
    spec:
      containers:
      - name: gruf
        image: gruf-relay:${VERSION}
        command: ["bundle", "exec", "gruf"]
        env:
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9394"
        - name: PROMETHEUS_EXPORTER_PATH
          value: /metrics
        - name: RAILS_LOG_LEVEL
          value: warn
        - name: RAILS_MAX_THREADS
          value: "5"
        - name: GRUF_BACKLOG_PATCH
          value: "${GRUF_BACKLOG_PATCH}"
        ports:
        - containerPort: 8080
        - containerPort: 5555
        - containerPort: 9394
        resources:
          requests:
            cpu: "250m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "400Mi"
        # startupProbe:
        #   httpGet:
        #     path: /startup
        #     port: 5555
        #   failureThreshold: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 5555
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /liveness
        #     port: 5555
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
