name: Go Release

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: '1.24'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binaries
        run: make build-binaries

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gruf-relay-binaries
          path: build/gruf-relay-*

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes

            See CHANGELOG.md for details.
            ```
          draft: false
          prerelease: false
          files: build/gruf-relay-*
